<a href="https://colab.research.google.com/github/arssite/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a=np.array([[1,2],[7,8]])

In [5]:
a

array([[1, 2],
       [7, 8]])

In [11]:
c=np.array([[5,6],[5,6],[5,6]])
c

array([[5, 6],
       [5, 6],
       [5, 6]])

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [18]:
x=MinMaxScaler(feature_range=(0,1))
n=x.fit(c)
m=x.transform(c)
print(type(n))
print(type(m))
print(m,n)

<class 'sklearn.preprocessing._data.MinMaxScaler'>
<class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]
 [0. 0.]] MinMaxScaler()


In [19]:
col=MinMaxScaler(feature_range=(0,1))
col.fit_transform(a)

array([[0., 0.],
       [1., 1.]])