<a href="https://colab.research.google.com/github/arssite/MachineLearning/blob/main/Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a=np.array([[1,2],[7,8]])

In [5]:
a

array([[1, 2],
       [7, 8]])

In [21]:
c=np.array([[5,6],[15,63],[55,67]])
c

array([[ 5,  6],
       [15, 63],
       [55, 67]])

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [23]:
x=MinMaxScaler(feature_range=(0,1))
n=x.fit(c)
m=x.transform(c)
print(type(n))
print(type(m))
print(m,n)

<class 'sklearn.preprocessing._data.MinMaxScaler'>
<class 'numpy.ndarray'>
[[0.         0.        ]
 [0.2        0.93442623]
 [1.         1.        ]] MinMaxScaler()


In [24]:
col=MinMaxScaler(feature_range=(0,1))
col.fit_transform(c)

array([[0.        , 0.        ],
       [0.2       , 0.93442623],
       [1.        , 1.        ]])

In [25]:
#ThresholdValue
from sklearn.preprocessing import Binarizer
x=np.array([[1,2,3],[4,5,6]])
sc=Binarizer(threshold=3)
sc.fit_transform(x)

array([[0, 0, 0],
       [1, 1, 1]])